--- # https://github.com/bitwalker/libcluster/issues/54
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-service-account


---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: myapp-role
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - list
      - get


---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: rolebinding-name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: myapp-role
subjects:
  - kind: ServiceAccount
    name: myapp-service-account


---
kind: Service
apiVersion: v1
metadata:
  name: exampleservice
spec:
  selector:
    app: myapp
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8000
      # Port to forward to inside the pod
      targetPort: 8000
      # Port accessible outside cluster
      nodePort: 32002
  type: LoadBalancer



---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      serviceAccountName: myapp-service-account
      containers:
        - name: myapp
          image: sdia/abento:latest
          imagePullPolicy: Always
          env:
            - name: REPLACE_OS_VARS
              value: 'true'
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8000
